### ISSUE TITLE
Please add a license.

### ISSUE THREAD

**Issue by Vinchethescript** [fazalfarhan01/EarnApp-API#7]
Hello! I was going to fork this project to add my modifications, but I noticed this code has no license. As of [Choose a License](https://choosealicense.com/no-permission/), I can fork the repository but can't use, modify, or share it. Could you add one, please? Thanks!

**Comment by fazalfarhan01** [comment]
Added [License](https://github.com/fazalfarhan01/EarnApp-API/blob/main/LICENSE.md)
